### ISSUE TITLE
No license declaration

### ISSUE THREAD

**Issue by rekado** [nboley/grit#1]
Hi,

I just packaged up GRIT for GNU Guix, but I cannot include the package in GNU Guix upstream because the GRIT sources do not declare any license.  Without an explicit free license the code falls under "all rights reserved" and thus is not Free Software and cannot be included in distributions that follow the [GNU Free System Distribution Guidelines](https://www.gnu.org/distros/free-system-distribution-guidelines.html), such as Fedora, Debian, and Guix System Distribution.

Under what license are the GRIT sources released?

GRIT includes Hull, which appears to be released under the [Expat license](http://directory.fsf.org/wiki/License:Expat).  Among compatible licenses for the combined work is the GNU GPL.

Cheers,
Ricardo

**Comment by nboley** [comment]
Hi Ricardo,

> I just packaged up GRIT for GNU Guix, but I cannot include the package in
> GNU Guix upstream because the GRIT sources do not declare any license.
> Without an explicit free license the code falls under "all rights reserved"
> and thus is not Free Software and cannot be included in distributions that
> follow the GNU Free System Distribution Guidelines
> https://www.gnu.org/distros/free-system-distribution-guidelines.html,
> such as Fedora, Debian, and Guix System Distribution.
> 
> Under what license are the GRIT sources released?
> 
> Thanks for point this out to me. I have always intended it to be GPL v3 -
> but I realize now that nothing actually says that. I'll update now.

Best, Nathan

**Comment by rekado** [comment]
Thank you very much for adding the notice and for releasing it under GPLv3+!
